
GRANT CONNECT, RESOURCE TO kh;

CREATE TABLE TB_MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(15) NOT NULL,
	TITLE_CODE CHAR(2) REFERENCES TB_TODO,
	MEMBER_ID VARCHAR2(30),
	MEMBER_PW VARCHAR2(30)
);

CREATE SEQUENCE SEQ_MEMBER_NO;

CREATE TABLE TB_TODO(
	CATEGORY CHAR(2) PRIMARY KEY,
	TODO VARCHAR2(30),
	DETAILS VARCHAR2(30),
	SET_DATE DATE DEFAULT SYSDATE,
	STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN('N', 'Y'))
);

-- 위에 거 XXXX--------------------------------------------------------------------------

CREATE TABLE TB_MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(15) NOT NULL,
	MEMBER_ID VARCHAR2(30) NOT NULL UNIQUE,
	MEMBER_PW VARCHAR2(30) NOT NULL
	);
	
DROP TABLE TB_MEMBER;
DROP TABLE TB_TODO;


CREATE TABLE TB_TODO(
  MEMBER_NO NUMBER REFERENCES TB_MEMBER (MEMBER_NO),
	TODO VARCHAR2(30),
	CATEGORY NUMBER,
	DETAILS VARCHAR2(30),
	STATUS CHAR CHECK(STATUS IN('N', 'Y')),
	SET_DATE DATE DEFAULT SYSDATE
);


SELECT * FROM TB_MEMBER
WHERE MEMBER_ID ='pqpq'
AND MEMBER_PW = '1212';


SELECT * FROM TB_MEMBER;
SELECT * FROM TB_TODO;


-- INSERT INTO TB_TODO VALUES('C1', '집안일', '빨래', DEFAULT, DEFAULT);
-- INSERT INTO TB_TODO VALUES('C2', '학업', '벨로그 작성', );

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM JOB;